name: Deploy Server
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        
      - name: Rename EB Config Files
        run : cd ./server && bash rename-ebextensions.sh 
        
      - name: Zip server folder
        run: cd ./server && zip -r ../deploy.zip . -x '*.git*'
        
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: pmt-backend
          environment_name: Pmt-backend-env
          version_label: pmt-server-api_${{github.SHA}}
          region: us-east-1
          deployment_package: deploy.zip
          use_existing_version_if_available: true
